server:
  port: ${PORT:8082}
spring:
     application:
       name: message-v1
     cloud:
       config:
         uri: http://localhost:8888
     profiles:
       active: dev
     redis:
       timeOfLife: 5000
management:
  endpoints:
    web:
      exposure:
        include: refresh
